create TABLE users(
   id SERIAL PRIMARY KEY NOT NULL,
   login VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   age INTEGER NOT NULL,
   isdeleted BOOLEAN DEFAULT FALSE
);

INSERT INTO USERS (ID, LOGIN, PASSWORD, AGE) VALUES (1, 'Tony', 'pw1', 25);
INSERT INTO USERS (ID, LOGIN, PASSWORD, AGE) VALUES (2, 'Tom', 'pw2', 29);
INSERT INTO USERS (ID, LOGIN, PASSWORD, AGE) VALUES (3, 'Tod', 'pw3', 35);
INSERT INTO USERS (ID, LOGIN, PASSWORD, AGE) VALUES (4, 'Jack', 'pw4', 30);
INSERT INTO USERS (ID, LOGIN, PASSWORD, AGE) VALUES (5, 'Jason', 'pw5', 31);
INSERT INTO USERS (ID, LOGIN, PASSWORD, AGE) VALUES (6, 'Justin', 'pw6', 33);
